Liste Çarpma

In [2]:
a = [1,2,3,4,5]
b = [2,3,4,5,6]
ab = []
for i in range(len(a)):
    ab.append(a[i]*b[i])

print(ab)

[2, 6, 12, 20, 30]


In [4]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([2,3,4,5,6])
print(a*b)

[ 2  6 12 20 30]


Array Oluşturma

In [7]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

b = np.array([3.22,5,6.444], dtype="int")
print(b)
print(type(b))

c = np.array([3,4,4.555,5.222], dtype="float")
print(c)
print(type(c))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[3 5 6]
<class 'numpy.ndarray'>
[3.    4.    4.555 5.222]
<class 'numpy.ndarray'>


In [8]:
a = np.zeros(10) #0 ile matris oluşturma
print(a)
a = np.zeros(10,dtype="float")
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
a = np.ones((3,5), dtype="int") #1 ile matris oluşturma
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [10]:
a = np.full((4,4),5,dtype="float") #istenilen değer için matris oluşturma
print(a)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [11]:
a = np.arange(0,32,3) # range ile liste oluşturma
print(a)

[ 0  3  6  9 12 15 18 21 24 27 30]


In [14]:
a = np.linspace(0,1,10) #belli iki değer için belli bir aralıkta liste oluşturma
print(a)

print("\n")
a = np.linspace(1,2, num=15,endpoint=False) #istenilen sayı kadar belli aralıkta matris oluşturma
print(a)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


[1.         1.06666667 1.13333333 1.2        1.26666667 1.33333333
 1.4        1.46666667 1.53333333 1.6        1.66666667 1.73333333
 1.8        1.86666667 1.93333333]


In [20]:
#random ile matris oluşturma
a = np.random.normal(10,5,(4,5)) #float
print(a)
print("\n")
a = np.random.random_integers(0,8,(5,3)) #in
print(a)
print("\n")
a = np.random.randint(10,size=10) #istenilen aralık kadar
print(a)

[[20.3370573   0.55041222 10.93145578  8.19969219 22.39821782]
 [-2.07228258  3.99112296 10.95855764  6.53466559 15.51826254]
 [ 6.24467403 11.41495777 19.92042948  3.31171368 15.15758881]
 [16.1920326   3.52309175  1.97095501 15.23402632  7.70712985]]


[[0 8 1]
 [7 3 1]
 [0 7 5]
 [4 2 1]
 [3 3 7]]


[8 1 8 9 7 0 4 7 8 4]


/tmp/ipykernel_11218/480539450.py:5: DeprecationWarning: This function is deprecated. Please call randint(0, 8 + 1) instead
  a = np.random.random_integers(0,8,(5,3)) #in


ÖZELLİKLER

In [23]:
a = np.random.randint(0,8,5)
print(a)
print("\n")
print(a.ndim) #boyut sayısı
print(a.shape) # ilk elemanlar
print(a.size) #boyut
print(a.dtype) #liste tipi

[1 0 5 7 1]


1
(5,)
5
int64


In [24]:
a = np.random.randint(4,10,size=(2,4))
print(a)
print(a.ndim)
print(a.size)
print(a.dtype)

[[8 8 7 7]
 [7 7 4 8]]
2
8
int64


Yeniden Şekillendirme

In [26]:
a = np.random.normal(10,5,15)
print(a)
print(a.ndim)
a = a.reshape((3,5))
print(a)
print(a.ndim)

[ 1.11536874 14.11425828 16.03241277 13.16689222 17.28660713  3.61054098
  9.79671781  6.10984672  9.72637085 15.98164838  6.00261191 20.90393238
 14.09871013 -5.48803239 11.83203226]
1
[[ 1.11536874 14.11425828 16.03241277 13.16689222 17.28660713]
 [ 3.61054098  9.79671781  6.10984672  9.72637085 15.98164838]
 [ 6.00261191 20.90393238 14.09871013 -5.48803239 11.83203226]]
2


İşlemler

In [27]:
#Array Birleştirme  - Concatenation
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
print(np.concatenate([x,y]))
z = np.array([7,8,9])
print(np.concatenate([x,y,z]))

[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8 9]


In [28]:
#Sıralama
a = np.random.randint(1,15,10)
print(a)
b = np.random.randint(1,15,10)
print(b.sort())
print(b)

[ 7  4 11  6  9  9  8  3  4 11]
None
[ 1  1  6  7 10 11 12 13 13 14]


In [29]:
m = np.random.randint(10,size=(3,5))
print(m)
print("\n")
print(m[2,3])

[[2 2 1 0 3]
 [4 2 5 4 6]
 [8 5 3 3 2]]


3


İki Boyutlu Dizi İşlemleri

In [30]:
m = np.random.randint(10,size=(5,5))
print(m)

[[8 0 4 2 8]
 [3 6 1 7 8]
 [4 7 8 5 4]
 [7 3 9 0 4]
 [4 6 2 5 5]]


In [40]:
print(m[0])
print(m[0,2:])
print(m[:,0])

print("\n")
print(m[1:4,1:4])
print("\n")
altkume = m[1:4,1:4].copy()
print(altkume)
print("\n")
print(altkume[2,1])
print(altkume<5)

[8 0 4 2 8]
[4 2 8]
[8 3 4 7 4]


[[6 1 7]
 [7 8 5]
 [3 9 0]]


[[6 1 7]
 [7 8 5]
 [3 9 0]]


9
[[False  True False]
 [False False False]
 [ True False  True]]


İstatiksel Hesaplamalar

In [65]:
print(np.mean(altkume))
print(np.sum(altkume))
print(np.var(altkume))

5.111111111111111
46
8.765432098765432
