In [1]:
import pandas as pd

In [5]:
a = pd.Series([10,88,3,4,5])
print(a)
print(type(a))
print(a.axes)
print(a.size)
print(a.ndim)
print(a.values)
print(a.head(3))
print(a.tail(3))

0    10
1    88
2     3
3     4
4     5
dtype: int64
<class 'pandas.core.series.Series'>
[RangeIndex(start=0, stop=5, step=1)]
5
1
[10 88  3  4  5]
0    10
1    88
2     3
dtype: int64
2    3
3    4
4    5
dtype: int64


Index İsimlendirilmesi

In [6]:
a = pd.Series([99,22,332,94,5], index=[1,3,5,7,9])
print(a)

1     99
3     22
5    332
7     94
9      5
dtype: int64


In [8]:
a = pd.Series([99,22,332,94,5],index=["a","b","c","d","e"])
print(a)
print(a["a"])
print(a["a":"c"])

a     99
b     22
c    332
d     94
e      5
dtype: int64
99
a     99
b     22
c    332
dtype: int64


İşlemler

In [11]:
#sozluk ile liste oluşturmak
sozluk = {"reg":10,"log":11,"cart":12}
seri = pd.Series(sozluk)
print(seri)

#serileri birleştir
seri = pd.concat([seri,seri])
print(seri)

reg     10
log     11
cart    12
dtype: int64
reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64


In [12]:
#numpy array ile pandas listesi oluşturmak
import numpy as np
a = np.array([1,2,33,444,75])
seri = pd.Series(a)
print(seri)

0      1
1      2
2     33
3    444
4     75
dtype: int64


In [13]:
print(seri[0])
print(seri[0:3])

1
0     1
1     2
2    33
dtype: int64


In [16]:
seri = pd.Series([121,200,150,99],index=["reg","loj","cart","rf"])
print(seri)
print(seri.index)
print(seri.keys)

reg     121
loj     200
cart    150
rf       99
dtype: int64
Index(['reg', 'loj', 'cart', 'rf'], dtype='object')
<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>


In [18]:
#eleman sorgulama
print("reg" in seri)
print("loh" in seri)

#eleman değiştirme
seri["reg"] = 30
print(seri["reg"])

True
False
30


Pandas ile Dataframe Oluşturma

In [20]:
import pandas as pd
listem = [1,2,39,67,90]
print(listem)

pd.DataFrame(listem,columns=["degisken_ismi"])

[1, 2, 39, 67, 90]


degisken_ismi
0              1
1              2
2             39
3             67
4             90

Pandas ve Numpy ile DataFrame Oluşturma

In [21]:
import numpy as np
x = np.arange(1,34)
print(x)
y = x.reshape(11,3)
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]


In [23]:
pd.DataFrame(y,columns=["var1","var2","var3"])

var1  var2  var3
0      1     2     3
1      4     5     6
2      7     8     9
3     10    11    12
4     13    14    15
5     16    17    18
6     19    20    21
7     22    23    24
8     25    26    27
9     28    29    30
10    31    32    33

In [25]:
df = pd.DataFrame(y,columns=["deg_1","deg_2","deg_3"])
print(df)

    deg_1  deg_2  deg_3
0       1      2      3
1       4      5      6
2       7      8      9
3      10     11     12
4      13     14     15
5      16     17     18
6      19     20     21
7      22     23     24
8      25     26     27
9      28     29     30
10     31     32     33


In [26]:
df.head(5)

deg_1  deg_2  deg_3
0      1      2      3
1      4      5      6
2      7      8      9
3     10     11     12
4     13     14     15

In [27]:
df.tail(5)

deg_1  deg_2  deg_3
6      19     20     21
7      22     23     24
8      25     26     27
9      28     29     30
10     31     32     33

In [28]:
print(type(df))
print(df.size)
print(df.axes)
print(df.shape)
print(df.values)

<class 'pandas.core.frame.DataFrame'>
33
[RangeIndex(start=0, stop=11, step=1), Index(['deg_1', 'deg_2', 'deg_3'], dtype='object')]
(11, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]


Koşullu Eleman İşlemleri

In [30]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30,size=(10,3))
print(m)

print("\n")

df = pd.DataFrame(m,columns=["var1","var2","var3"])
df

[[22 18 28]
 [19 22 25]
 [16 13 20]
 [16  3 27]
 [28 16 22]
 [23  9  9]
 [25 10 27]
 [11 19 15]
 [22 28 12]
 [ 8 10 14]]




var1  var2  var3
0    22    18    28
1    19    22    25
2    16    13    20
3    16     3    27
4    28    16    22
5    23     9     9
6    25    10    27
7    11    19    15
8    22    28    12
9     8    10    14

In [33]:
df["var1"]

0    22
1    19
2    16
3    16
4    28
5    23
6    25
7    11
8    22
9     8
Name: var1, dtype: int64

In [34]:
df.var1

0    22
1    19
2    16
3    16
4    28
5    23
6    25
7    11
8    22
9     8
Name: var1, dtype: int64

In [35]:
df[df.var1>15]

var1  var2  var3
0    22    18    28
1    19    22    25
2    16    13    20
3    16     3    27
4    28    16    22
5    23     9     9
6    25    10    27
8    22    28    12

In [36]:
df[(df.var1>15) & (df.var2<10)]

var1  var2  var3
3    16     3    27
5    23     9     9

Birleşitirme Join İşlemleri

In [39]:
m = np.random.randint(1,30,size=(5,3))
df1 = pd.DataFrame(m,columns=["var1","var2","var3"])
df1

var1  var2  var3
0     1    19    28
1    12    12     5
2    28    26    22
3     9    12     3
4    20    20     1

In [40]:
df2 = df1+55
df2

var1  var2  var3
0    56    74    83
1    67    67    60
2    83    81    77
3    64    67    58
4    75    75    56

In [41]:
pd.concat([df1,df2])

var1  var2  var3
0     1    19    28
1    12    12     5
2    28    26    22
3     9    12     3
4    20    20     1
0    56    74    83
1    67    67    60
2    83    81    77
3    64    67    58
4    75    75    56

In [46]:
pd.concat([df1,df2],ignore_index=False) # sıfırdan başlatma ikinci

var1  var2  var3
0     1    19    28
1    12    12     5
2    28    26    22
3     9    12     3
4    20    20     1
0    56    74    83
1    67    67    60
2    83    81    77
3    64    67    58
4    75    75    56

In [47]:
pd.concat([df1,df2],ignore_index=True) #sıfırdan başlatmayı engelle ikinci

var1  var2  var3
0     1    19    28
1    12    12     5
2    28    26    22
3     9    12     3
4    20    20     1
5    56    74    83
6    67    67    60
7    83    81    77
8    64    67    58
9    75    75    56

İleri Birleştirme

In [48]:
df1 = pd.DataFrame({'calisanlar': ['Ali', 'Veli', 'Ayse', 'Fatma'],'grup': ['Muhasebe', 'Muhendislik', 'Muhendislik', 'İK']})
df2 = pd.DataFrame({'calisanlar': ['Ayse', 'Ali', 'Veli', 'Fatma'], 'ilk_giris': [2010, 2009, 2014, 2019]})

In [49]:
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [50]:
df2

calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [51]:
pd.merge(df1,df2)

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [54]:
df3=pd.merge(df1, df2)
print(df3)
df4 = pd.DataFrame({'grup': ['Muhasebe', 'Muhendislik', 'İK'],'mudur': ['Caner', 'Mustafa', 'Berkcan']})
print(df4)

  calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019
          grup    mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           İK  Berkcan


In [55]:
pd.merge(df3,df4)

calisanlar         grup  ilk_giris    mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayse  Muhendislik       2010  Mustafa
3      Fatma           İK       2019  Berkcan